/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : CZT Harmonic Analyser + Power + OLED — STM32G474RE
  *
  * @overview
  *   This firmware implements a real-time AC power quality analyser on the
  *   STM32G474RE Nucleo board. It simultaneously captures voltage (ZMPT101B)
  *   and current (WCS1700) waveforms via dual-mode simultaneous ADC sampling,
  *   then applies a Chirp Z-Transform (CZT) to resolve harmonics H1–H10
  *   (50 Hz–500 Hz) with 0.5 Hz frequency resolution.
  *
  * @hardware_connections
  *   ┌──────────────────────┬──────────────────────────────────────────────┐
  *   │ Signal               │ Pin / Peripheral                             │
  *   ├──────────────────────┼──────────────────────────────────────────────┤
  *   │ Voltage (ZMPT101B)   │ PA0  → ADC1 Channel 1  (5 V + 10k/10k div)  │
  *   │ Current (WCS1700)    │ PA6  → ADC2 Channel 6  (5 V + 10k/10k div)  │
  *   │ Sample clock         │ TIM1 TRGO @ 10 kHz                           │
  *   │ OLED display         │ I2C1  (SSD1306, 128×64)                      │
  *   │ Debug UART           │ LPUART1 @ 209700 baud (ST-Link VCP)          │
  *   │ Status LED           │ LD2 (PA5) — toggles every processed frame    │
  *   └──────────────────────┴──────────────────────────────────────────────┘
  *
  * @signal_chain
  *   TIM1 TRGO (10 kHz)
  *     → ADC1 + ADC2 simultaneous trigger (Dual Regular Simultaneous mode)
  *     → DMA1 Ch1 packs both 12-bit results into one 32-bit word per sample
  *       (ADC1 in bits[15:0], ADC2 in bits[31:16])
  *     → 1000-sample ping-pong frame in adc_dual_buf[]
  *     → HAL_ADC_ConvCpltCallback raises capture_done flag
  *     → Main loop calls Process_Buffer()
  *         ├─ Split channels, compute DC bias (peak-averaging method)
  *         ├─ RMS (time-domain), zero-crossing frequency
  *         ├─ CZT on voltage (Hann-windowed) → H1-H10 amplitudes + THD
  *         ├─ CZT on current (rectangular window) → H1-H10 amplitudes + THD
  *         ├─ Instantaneous-product active power, apparent power, PF, phase
  *         └─ OLED refresh + UART frame dump
  *
  * @calibration_notes
  *   Voltage:  CAL_FACTOR_V = 623.81   (accounts for ZMPT101B turns ratio
  *             and 10k/10k resistor divider)
  *   Current:  V0G_COUNTS_CAL = 1437   (ADC count at zero-current; set during
  *             Step-1 zero calibration with no load)
  *             CAL_GAIN       = 0.923410 (gain trim; set during Step-2 load
  *             calibration against a known reference current)
  *
  * @dependencies
  *   - ARM CMSIS-DSP   (arm_math.h  — for arm_math types; CZT is hand-coded)
  *   - SSD1306 driver  (ssd1306.h   — I2C-DMA OLED library)
  *   - STM32 HAL G4    (generated by CubeMX)
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "ssd1306.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* ── Acquisition parameters ────────────────────────────────────────────── */
#define SAMPLE_COUNT    1000U               /* Samples per captured frame     */
#define KERN_LEN        (2U * SAMPLE_COUNT - 1U)   /* CZT kernel length = 1999 */
#define VREF            3.3f               /* STM32 ADC reference voltage (V) */
#define ADC_RES         4096.0f            /* 12-bit ADC full-scale counts    */
#define SAMPLE_RATE     10000.0f           /* ADC sample rate (Hz)            */
#define NUM_HARMONICS   10                 /* Number of harmonics to resolve  */

/* ── Voltage channel calibration ───────────────────────────────────────── */
/* CAL_FACTOR_V converts ADC RMS counts → true AC RMS volts.
 * It combines the ZMPT101B transformer turns ratio and the 10k/10k
 * resistive voltage divider at the ADC input.                               */
#define CAL_FACTOR_V    623.81f

/* ── Current channel calibration ───────────────────────────────────────── */
/* The WCS1700 Hall-effect sensor outputs ±33 mV/A centred on Vcc/2 (2.5 V).
 * A 10k/10k resistive divider halves the sensor swing before the ADC.      */
#define DIVIDER_RATIO           0.5f               /* Resistive divider ratio  */
#define SENS_MV_PER_A_SENSOR    33.0f              /* Sensor sensitivity mV/A  */
#define V0G_SENSOR_V            2.500f             /* Sensor zero-current voltage (V) */
#define SENS_MV_PER_A_ADC       (SENS_MV_PER_A_SENSOR * DIVIDER_RATIO)  /* 16.5 mV/A after divider */

/* Zero-current ADC count (mid-scale after divider ≈ 1437).
 * Update this after Step-1 zero calibration (no load connected).           */
#define V0G_COUNTS_CAL          1437.0f

/* Gain trim factor measured during Step-2 load calibration.
 * Update after comparing IRMS reading against a trusted reference.         */
#define CAL_GAIN                0.923410f

/**
 * @brief  Convert a zero-referenced ADC count difference to amperes.
 * @param  c   ADC count offset from zero-current point (signed float)
 * @return Current in amperes (float)
 *
 * Formula:
 *   I = (c × Vref/ADC_RES) / (SENS_mV/A_adc × 1e-3)  × CAL_GAIN
 */
#define COUNTS_TO_AMPS(c) \
    ((c) * (VREF / ADC_RES) / (SENS_MV_PER_A_ADC * 1e-3f) * CAL_GAIN)

/* ── CZT (Chirp Z-Transform) parameters ────────────────────────────────── */
/* The CZT maps SAMPLE_COUNT time-domain samples to SAMPLE_COUNT frequency
 * bins spanning [0, CZT_DELTA_F] Hz with resolution CZT_FREQ_RES.
 * At 10 kHz / 1000 points the Nyquist is 5 kHz, but we only need 0–500 Hz
 * to cover H1(50 Hz) through H10(500 Hz).                                  */
#define CZT_DELTA_F     500.0f                     /* CZT span: 0–500 Hz      */
#define CZT_FREQ_RES    (CZT_DELTA_F / (float)SAMPLE_COUNT)   /* 0.5 Hz/bin  */
/* Angular step between adjacent CZT output bins (radians):
 *   C = π × Δf / (N × fs)   ≈ 1.571e-4 rad                                 */
#define CZT_C           ((float)M_PI * CZT_DELTA_F \
                         / ((float)SAMPLE_COUNT * SAMPLE_RATE))

/* ── Harmonic search ────────────────────────────────────────────────────── */
#define FUNDAMENTAL_HZ  50U    /* Expected mains fundamental frequency (Hz)  */
#define SEARCH_BINS     4U     /* ±4 bins around ideal harmonic bin to track
                                *  small frequency deviations                */

/* ── Zero-crossing hysteresis ───────────────────────────────────────────── */
/* Prevents noise-induced false crossings near the DC bias level.
 * The signal must cross bias ± HYST before a transition is counted.        */
#define ZC_HYST_V       25.0f  /* Voltage channel (ZMPT101B) — ADC counts    */
#define ZC_HYST_I       12.0f  /* Current channel (WCS1700)  — ADC counts    */

/* ── DC bias estimation ─────────────────────────────────────────────────── */
/* The bias is estimated as (avg_of_N_lowest + avg_of_N_highest) / 2.
 * PEAK_AVG_COUNT controls how many extremes are averaged to reduce the
 * impact of individual noise spikes on the bias estimate.                   */
#define PEAK_AVG_COUNT  10

/* ── TX ping-pong UART buffer ───────────────────────────────────────────── */
/* Two buffers allow one frame to be assembled while the previous is being
 * transmitted via interrupt-driven UART, eliminating blocking delays.      */
#define TX_BUF_SIZE     2048U
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
ADC_HandleTypeDef hadc1;
ADC_HandleTypeDef hadc2;
DMA_HandleTypeDef hdma_adc1;

I2C_HandleTypeDef hi2c1;
DMA_HandleTypeDef hdma_i2c1_tx;

UART_HandleTypeDef hlpuart1;

RTC_HandleTypeDef hrtc;

TIM_HandleTypeDef htim1;

/* USER CODE BEGIN PV */
/* ── ADC DMA buffer ─────────────────────────────────────────────────────── */
static uint32_t  adc_dual_buf[SAMPLE_COUNT];
volatile uint8_t capture_done = 0;

/* ── CZT arrays  ──────────────────────── */
static float tw_n_re[SAMPLE_COUNT];
static float tw_n_im[SAMPLE_COUNT];
static float kern_re[KERN_LEN];
static float kern_im[KERN_LEN];
static float hann_win_v[SAMPLE_COUNT];
static float rect_win_i[SAMPLE_COUNT];
static float g_re[SAMPLE_COUNT];
static float g_im[SAMPLE_COUNT];
static float czt_mag[SAMPLE_COUNT];

/* ── UART ping-pong TX buffers ──────────────────────────────────────────── */
static uint8_t          tx_buf[2][TX_BUF_SIZE];
static uint16_t         tx_len[2]      = {0, 0};
static uint8_t          tx_write_idx   = 0;
static uint8_t          tx_read_idx    = 0;
static volatile uint8_t tx_busy        = 0;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_ADC1_Init(void);
static void MX_LPUART1_UART_Init(void);
static void MX_TIM1_Init(void);
static void MX_ADC2_Init(void);
static void MX_I2C1_Init(void);
static void MX_RTC_Init(void);
/* USER CODE BEGIN PFP */
/* ── UART  ── */
static void UART_Print_IT(const char *msg);
static void UART_Flush_IT(void);
void        HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart);

/* ── ADC  ── */
void        HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc);

/* ── Needed by shared Process_Buffer ── */
void        HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef *hi2c);
static int  Find_Peak_Bin(int expected_bin);
static void CZT_Init(void);
static void CZT_Compute_From_Buffer(const float *buf, float bias, const float *win);
static void Compute_CZT_Harmonics_V(float freq);
static void Compute_CZT_Harmonics_I(float freq);
static void Process_Buffer(void);
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* ── OLED I2C Callback ───────────────────────────────────────────────────── */
/**
 * @brief  HAL I2C master TX-complete callback.
 *         Forwards the event to the SSD1306 driver so it can pipeline
 *         the next DMA chunk (multi-page transfers are split internally).
 * @param  hi2c  Pointer to the I2C handle that fired the callback.
 */
void HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    SSD1306_TxCpltCallback(hi2c);
}



/* ════════════════════════════════════════════════════════════════════════
 * UART PING-PONG TX SYSTEM
 * ════════════════════════════════════════════════════════════════════════ */

/**
 * @brief  Append a string to the active write buffer (non-blocking).
 */
static void UART_Print_IT(const char *msg)
{
    uint16_t len  = (uint16_t)strlen(msg);
    uint16_t used = tx_len[tx_write_idx];
    if (used + len > TX_BUF_SIZE) return;
    memcpy(&tx_buf[tx_write_idx][used], msg, len);
    tx_len[tx_write_idx] = used + len;
}

/**
 * @brief  Swap ping-pong buffers and start interrupt-driven UART TX.
 */
static void UART_Flush_IT(void)
{
    if (tx_len[tx_write_idx] == 0) return;

    if (!tx_busy)
    {
        tx_read_idx          = tx_write_idx;
        tx_write_idx         = tx_write_idx ^ 1U;
        tx_len[tx_write_idx] = 0;
        tx_busy = 1;
        HAL_UART_Transmit_IT(&hlpuart1,
                             tx_buf[tx_read_idx],
                             tx_len[tx_read_idx]);
    }
}

/**
 * @brief  UART TX-complete callback — auto-chains next buffer if pending.
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance != LPUART1) return;

    tx_len[tx_read_idx] = 0;

    uint8_t next = tx_read_idx ^ 1U;
    if (tx_len[next] > 0)
    {
        tx_read_idx          = next;
        tx_write_idx         = tx_read_idx ^ 1U;
        tx_len[tx_write_idx] = 0;
        HAL_UART_Transmit_IT(&hlpuart1,
                             tx_buf[tx_read_idx],
                             tx_len[tx_read_idx]);
    }
    else
    {
        tx_busy = 0;
    }
}

/* ════════════════════════════════════════════════════════════════════════
 *  ADC DMA CALLBACK
 * ════════════════════════════════════════════════════════════════════════ */

/**
 * @brief  DMA transfer-complete callback.
 *         Sets capture_done so the main loop calls Process_Buffer().
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        capture_done = 1;
    }
}


 /* ================================================================
         * OLED DISPLAY UPDATE
         * ============================================================== */
        /* Only update the display if the SSD1306 I2C DMA is idle.
         * SSD1306_IsReady() returns false while a previous frame transfer
         * is still in progress, preventing I2C bus contention.             */
        if (SSD1306_IsReady())
        {
            char oled_v[32];
            char oled_i[32];
            char oled_p[32];
            char oled_pf[32];

            snprintf(oled_v,  sizeof(oled_v),  "Vrms : %.1f V", (double)vrms);
            snprintf(oled_i,  sizeof(oled_i),  "Irms : %.2f A", (double)irms);
            snprintf(oled_p,  sizeof(oled_p),  "Power: %.1f W", (double)active_power);
            snprintf(oled_pf, sizeof(oled_pf), "PF   : %.2f",   (double)power_factor);

            SSD1306_Clear();

            /* Page 0: Title */
            SSD1306_WriteString(0, 0, "-- Power Monitor --");

            /* Pages 2 & 3: Voltage and Current */
            SSD1306_WriteString(0, 2, oled_v);
            SSD1306_WriteString(0, 3, oled_i);

            /* Pages 5 & 6: Power and Power Factor */
            SSD1306_WriteString(0, 5, oled_p);
            SSD1306_WriteString(0, 6, oled_pf);

            SSD1306_UpdateScreen();
        }
    }

    /* Single flush — kicks off IT transfer for the whole assembled frame    */
    UART_Print_IT("----------------------------------------\r\n");
    UART_Flush_IT();

    /* ── FIX: Clear Hardware Overrun flags before re-arming ── */
    /* ADC overrun (OVR) occurs when a new conversion completes before the
     * previous result was read. Clearing OVR here prevents the next DMA
     * capture from being suppressed by a stale overrun condition.           */
    __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_OVR);
    __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_OVR);

    /* ── Re-arm DMA ── */
    /* Restart dual simultaneous ADC DMA capture for the next frame.
     * TIM1 TRGO continues running so conversion timing is uninterrupted.   */
    HAL_ADCEx_MultiModeStart_DMA(&hadc1, (uint32_t *)adc_dual_buf, SAMPLE_COUNT);
}

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_ADC1_Init();
  MX_LPUART1_UART_Init();
  MX_TIM1_Init();
  MX_ADC2_Init();
  MX_I2C1_Init();
  MX_RTC_Init();
  /* USER CODE BEGIN 2 */

    /* ── OLED splash screen ── */
    SSD1306_Init(&hi2c1);
    SSD1306_Clear();
    SSD1306_WriteString(0, 0, "Booting...");
    SSD1306_UpdateScreen();
    HAL_Delay(500);   /* Allow OLED DMA transfer to complete before continuing */


/* ── CZT precompute  ── */
CZT_Init();

/* ── ADC self-calibration  ── */
HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED);
HAL_ADCEx_Calibration_Start(&hadc2, ADC_SINGLE_ENDED);

/* ── Startup UART banner ── */
UART_Print_IT("\r\n=== CZT Simultaneous V+I Harmonic Analyser (G474RE) ===\r\n");
UART_Print_IT("[V] ZMPT101B 5V + 10k/10k divider -> PA0  (ADC1_IN1)\r\n");
UART_Print_IT("[I] WCS1700  5V + 10k/10k divider -> PA6  (ADC2_IN3)\r\n");
UART_Print_IT("fs=10kHz  N=1000  Df=500Hz  fR=0.5Hz\r\n");
UART_Print_IT("Dual Regular Simultaneous mode, TIM1 TRGO trigger\r\n");
UART_Print_IT("H1(50Hz)..H10(500Hz) + THD  per channel\r\n");
UART_Print_IT("-------------------------------------------------------\r\n");
UART_Flush_IT();

/* ── Start dual ADC DMA capture  ── */
HAL_ADCEx_MultiModeStart_DMA(&hadc1, (uint32_t *)adc_dual_buf, SAMPLE_COUNT);
HAL_TIM_Base_Start(&htim1);

/* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    /* Poll the flag set by HAL_ADC_ConvCpltCallback.
     * When set, the DMA has filled adc_dual_buf with SAMPLE_COUNT samples.
     * Clear immediately so a new capture can begin inside Process_Buffer().  */
    if (capture_done)
    {
        capture_done = 0;
        HAL_GPIO_TogglePin(LD2_GPIO_Port, LD2_Pin); /* Heartbeat LED toggle */
        Process_Buffer();
    }
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_LSI|RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV6;
  RCC_OscInitStruct.PLL.PLLN = 85;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief ADC1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC1_Init(void)
{

  /* USER CODE BEGIN ADC1_Init 0 */

  /* USER CODE END ADC1_Init 0 */

  ADC_MultiModeTypeDef multimode = {0};
  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC1_Init 1 */

  /* USER CODE END ADC1_Init 1 */

  /** Common config
  */
  hadc1.Instance = ADC1;
  hadc1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
  hadc1.Init.Resolution = ADC_RESOLUTION_12B;
  hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc1.Init.GainCompensation = 0;
  hadc1.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc1.Init.LowPowerAutoWait = DISABLE;
  hadc1.Init.ContinuousConvMode = DISABLE;
  hadc1.Init.NbrOfConversion = 1;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.ExternalTrigConv = ADC_EXTERNALTRIG_T1_TRGO;
  hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_RISING;
  hadc1.Init.DMAContinuousRequests = ENABLE;
  hadc1.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  hadc1.Init.OversamplingMode = DISABLE;
  if (HAL_ADC_Init(&hadc1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure the ADC multi-mode
  */
  multimode.Mode = ADC_DUALMODE_REGSIMULT;
  multimode.DMAAccessMode = ADC_DMAACCESSMODE_12_10_BITS;
  multimode.TwoSamplingDelay = ADC_TWOSAMPLINGDELAY_1CYCLE;
  if (HAL_ADCEx_MultiModeConfigChannel(&hadc1, &multimode) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_1;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_24CYCLES_5;
  sConfig.SingleDiff = ADC_SINGLE_ENDED;
  sConfig.OffsetNumber = ADC_OFFSET_NONE;
  sConfig.Offset = 0;
  if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC1_Init 2 */

  /* USER CODE END ADC1_Init 2 */

}

/**
  * @brief ADC2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC2_Init(void)
{

  /* USER CODE BEGIN ADC2_Init 0 */

  /* USER CODE END ADC2_Init 0 */

  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC2_Init 1 */

  /* USER CODE END ADC2_Init 1 */

  /** Common config
  */
  hadc2.Instance = ADC2;
  hadc2.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
  hadc2.Init.Resolution = ADC_RESOLUTION_12B;
  hadc2.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc2.Init.GainCompensation = 0;
  hadc2.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc2.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc2.Init.LowPowerAutoWait = DISABLE;
  hadc2.Init.ContinuousConvMode = DISABLE;
  hadc2.Init.NbrOfConversion = 1;
  hadc2.Init.DiscontinuousConvMode = DISABLE;
  hadc2.Init.DMAContinuousRequests = DISABLE;
  hadc2.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  hadc2.Init.OversamplingMode = DISABLE;
  if (HAL_ADC_Init(&hadc2) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_6;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_24CYCLES_5;
  sConfig.SingleDiff = ADC_SINGLE_ENDED;
  sConfig.OffsetNumber = ADC_OFFSET_NONE;
  sConfig.Offset = 0;
  if (HAL_ADC_ConfigChannel(&hadc2, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC2_Init 2 */

  /* USER CODE END ADC2_Init 2 */

}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.Timing = 0x40B285C2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Analogue filter
  */
  if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Digital filter
  */
  if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief LPUART1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_LPUART1_UART_Init(void)
{

  /* USER CODE BEGIN LPUART1_Init 0 */

  /* USER CODE END LPUART1_Init 0 */

  /* USER CODE BEGIN LPUART1_Init 1 */

  /* USER CODE END LPUART1_Init 1 */
  hlpuart1.Instance = LPUART1;
  hlpuart1.Init.BaudRate = 209700;
  hlpuart1.Init.WordLength = UART_WORDLENGTH_8B;
  hlpuart1.Init.StopBits = UART_STOPBITS_1;
  hlpuart1.Init.Parity = UART_PARITY_NONE;
  hlpuart1.Init.Mode = UART_MODE_TX_RX;
  hlpuart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  hlpuart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  hlpuart1.Init.ClockPrescaler = UART_PRESCALER_DIV1;
  hlpuart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&hlpuart1) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetTxFifoThreshold(&hlpuart1, UART_TXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetRxFifoThreshold(&hlpuart1, UART_RXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_DisableFifoMode(&hlpuart1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN LPUART1_Init 2 */

  /* USER CODE END LPUART1_Init 2 */

}

/**
  * @brief RTC Initialization Function
  * @param None
  * @retval None
  */
static void MX_RTC_Init(void)
{

  /* USER CODE BEGIN RTC_Init 0 */

  /* USER CODE END RTC_Init 0 */

  RTC_TimeTypeDef sTime = {0};
  RTC_DateTypeDef sDate = {0};

  /* USER CODE BEGIN RTC_Init 1 */

  /* USER CODE END RTC_Init 1 */

  /** Initialize RTC Only
  */
  hrtc.Instance = RTC;
  hrtc.Init.HourFormat = RTC_HOURFORMAT_24;
  hrtc.Init.AsynchPrediv = 127;
  hrtc.Init.SynchPrediv = 255;
  hrtc.Init.OutPut = RTC_OUTPUT_DISABLE;
  hrtc.Init.OutPutRemap = RTC_OUTPUT_REMAP_NONE;
  hrtc.Init.OutPutPolarity = RTC_OUTPUT_POLARITY_HIGH;
  hrtc.Init.OutPutType = RTC_OUTPUT_TYPE_OPENDRAIN;
  hrtc.Init.OutPutPullUp = RTC_OUTPUT_PULLUP_NONE;
  if (HAL_RTC_Init(&hrtc) != HAL_OK)
  {
    Error_Handler();
  }

  /* USER CODE BEGIN Check_RTC_BKUP */

  /* USER CODE END Check_RTC_BKUP */

  /** Initialize RTC and set the Time and Date
  */
  sTime.Hours = 2;
  sTime.Minutes = 10;
  sTime.Seconds = 0;
  sTime.SubSeconds = 0;
  sTime.DayLightSaving = RTC_DAYLIGHTSAVING_NONE;
  sTime.StoreOperation = RTC_STOREOPERATION_RESET;
  if (HAL_RTC_SetTime(&hrtc, &sTime, RTC_FORMAT_BIN) != HAL_OK)
  {
    Error_Handler();
  }
  sDate.WeekDay = RTC_WEEKDAY_MONDAY;
  sDate.Month = RTC_MONTH_MARCH;
  sDate.Date = 12;
  sDate.Year = 26;

  if (HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BIN) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN RTC_Init 2 */

  /* USER CODE END RTC_Init 2 */

}

/**
  * @brief TIM1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM1_Init(void)
{

  /* USER CODE BEGIN TIM1_Init 0 */

  /* USER CODE END TIM1_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};
  TIM_BreakDeadTimeConfigTypeDef sBreakDeadTimeConfig = {0};

  /* USER CODE BEGIN TIM1_Init 1 */

  /* USER CODE END TIM1_Init 1 */
  htim1.Instance = TIM1;
  htim1.Init.Prescaler = 0;
  htim1.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim1.Init.Period = 16999;
  htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim1.Init.RepetitionCounter = 0;
  htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
  if (HAL_TIM_Base_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim1, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_UPDATE;
  sMasterConfig.MasterOutputTrigger2 = TIM_TRGO2_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim1, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCNPolarity = TIM_OCNPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  sConfigOC.OCIdleState = TIM_OCIDLESTATE_RESET;
  sConfigOC.OCNIdleState = TIM_OCNIDLESTATE_RESET;
  if (HAL_TIM_PWM_ConfigChannel(&htim1, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
  sBreakDeadTimeConfig.OffStateRunMode = TIM_OSSR_DISABLE;
  sBreakDeadTimeConfig.OffStateIDLEMode = TIM_OSSI_DISABLE;
  sBreakDeadTimeConfig.LockLevel = TIM_LOCKLEVEL_OFF;
  sBreakDeadTimeConfig.DeadTime = 0;
  sBreakDeadTimeConfig.BreakState = TIM_BREAK_DISABLE;
  sBreakDeadTimeConfig.BreakPolarity = TIM_BREAKPOLARITY_HIGH;
  sBreakDeadTimeConfig.BreakFilter = 0;
  sBreakDeadTimeConfig.BreakAFMode = TIM_BREAK_AFMODE_INPUT;
  sBreakDeadTimeConfig.Break2State = TIM_BREAK2_DISABLE;
  sBreakDeadTimeConfig.Break2Polarity = TIM_BREAK2POLARITY_HIGH;
  sBreakDeadTimeConfig.Break2Filter = 0;
  sBreakDeadTimeConfig.Break2AFMode = TIM_BREAK_AFMODE_INPUT;
  sBreakDeadTimeConfig.AutomaticOutput = TIM_AUTOMATICOUTPUT_DISABLE;
  if (HAL_TIMEx_ConfigBreakDeadTime(&htim1, &sBreakDeadTimeConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM1_Init 2 */

  /* USER CODE END TIM1_Init 2 */

}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void)
{

  /* DMA controller clock enable */
  __HAL_RCC_DMAMUX1_CLK_ENABLE();
  __HAL_RCC_DMA1_CLK_ENABLE();

  /* DMA interrupt init */
  /* DMA1_Channel1_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel1_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel1_IRQn);
  /* DMA1_Channel2_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel2_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel2_IRQn);

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin_Pin */
  GPIO_InitStruct.Pin = B1_Pin_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(B1_Pin_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LD2_Pin */
  GPIO_InitStruct.Pin = LD2_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LD2_GPIO_Port, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
