/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : CZT Harmonic Analyser + Power + OLED — STM32G474RE
  *
  * @overview
  *   This firmware implements a real-time AC power quality analyser on the
  *   STM32G474RE Nucleo board. It simultaneously captures voltage (ZMPT101B)
  *   and current (WCS1700) waveforms via dual-mode simultaneous ADC sampling,
  *   then applies a Chirp Z-Transform (CZT) to resolve harmonics H1–H10
  *   (50 Hz–500 Hz) with 0.5 Hz frequency resolution.
  *
  * @hardware_connections
  *   ┌──────────────────────┬──────────────────────────────────────────────┐
  *   │ Signal               │ Pin / Peripheral                             │
  *   ├──────────────────────┼──────────────────────────────────────────────┤
  *   │ Voltage (ZMPT101B)   │ PA0  → ADC1 Channel 1  (5 V + 10k/10k div)  │
  *   │ Current (WCS1700)    │ PA6  → ADC2 Channel 6  (5 V + 10k/10k div)  │
  *   │ Sample clock         │ TIM1 TRGO @ 10 kHz                           │
  *   │ OLED display         │ I2C1  (SSD1306, 128×64)                      │
  *   │ Debug UART           │ LPUART1 @ 209700 baud (ST-Link VCP)          │
  *   │ Status LED           │ LD2 (PA5) — toggles every processed frame    │
  *   └──────────────────────┴──────────────────────────────────────────────┘
  *
  * @signal_chain
  *   TIM1 TRGO (10 kHz)
  *     → ADC1 + ADC2 simultaneous trigger (Dual Regular Simultaneous mode)
  *     → DMA1 Ch1 packs both 12-bit results into one 32-bit word per sample
  *       (ADC1 in bits[15:0], ADC2 in bits[31:16])
  *     → 1000-sample ping-pong frame in adc_dual_buf[]
  *     → HAL_ADC_ConvCpltCallback raises capture_done flag
  *     → Main loop calls Process_Buffer()
  *         ├─ Split channels, compute DC bias (peak-averaging method)
  *         ├─ RMS (time-domain), zero-crossing frequency
  *         ├─ CZT on voltage (Hann-windowed) → H1-H10 amplitudes + THD
  *         ├─ CZT on current (rectangular window) → H1-H10 amplitudes + THD
  *         ├─ Instantaneous-product active power, apparent power, PF, phase
  *         └─ OLED refresh + UART frame dump
  *
  * @calibration_notes
  *   Voltage:  CAL_FACTOR_V = 623.81   (accounts for ZMPT101B turns ratio
  *             and 10k/10k resistor divider)
  *   Current:  V0G_COUNTS_CAL = 1437   (ADC count at zero-current; set during
  *             Step-1 zero calibration with no load)
  *             CAL_GAIN       = 0.923410 (gain trim; set during Step-2 load
  *             calibration against a known reference current)
  *
  * @dependencies
  *   - ARM CMSIS-DSP   (arm_math.h  — for arm_math types; CZT is hand-coded)
  *   - SSD1306 driver  (ssd1306.h   — I2C-DMA OLED library)
  *   - STM32 HAL G4    (generated by CubeMX)
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "ssd1306.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* ── Acquisition parameters ────────────────────────────────────────────── */
#define SAMPLE_COUNT    1000U               /* Samples per captured frame     */
#define KERN_LEN        (2U * SAMPLE_COUNT - 1U)   /* CZT kernel length = 1999 */
#define VREF            3.3f               /* STM32 ADC reference voltage (V) */
#define ADC_RES         4096.0f            /* 12-bit ADC full-scale counts    */
#define SAMPLE_RATE     10000.0f           /* ADC sample rate (Hz)            */
#define NUM_HARMONICS   10                 /* Number of harmonics to resolve  */

/* ── Voltage channel calibration ───────────────────────────────────────── */
/* CAL_FACTOR_V converts ADC RMS counts → true AC RMS volts.
 * It combines the ZMPT101B transformer turns ratio and the 10k/10k
 * resistive voltage divider at the ADC input.                               */
#define CAL_FACTOR_V    623.81f

/* ── Current channel calibration ───────────────────────────────────────── */
/* The WCS1700 Hall-effect sensor outputs ±33 mV/A centred on Vcc/2 (2.5 V).
 * A 10k/10k resistive divider halves the sensor swing before the ADC.      */
#define DIVIDER_RATIO           0.5f               /* Resistive divider ratio  */
#define SENS_MV_PER_A_SENSOR    33.0f              /* Sensor sensitivity mV/A  */
#define V0G_SENSOR_V            2.500f             /* Sensor zero-current voltage (V) */
#define SENS_MV_PER_A_ADC       (SENS_MV_PER_A_SENSOR * DIVIDER_RATIO)  /* 16.5 mV/A after divider */

/* Zero-current ADC count (mid-scale after divider ≈ 1437).
 * Update this after Step-1 zero calibration (no load connected).           */
#define V0G_COUNTS_CAL          1437.0f

/* Gain trim factor measured during Step-2 load calibration.
 * Update after comparing IRMS reading against a trusted reference.         */
#define CAL_GAIN                0.923410f

/**
 * @brief  Convert a zero-referenced ADC count difference to amperes.
 * @param  c   ADC count offset from zero-current point (signed float)
 * @return Current in amperes (float)
 *
 * Formula:
 *   I = (c × Vref/ADC_RES) / (SENS_mV/A_adc × 1e-3)  × CAL_GAIN
 */
#define COUNTS_TO_AMPS(c) \
    ((c) * (VREF / ADC_RES) / (SENS_MV_PER_A_ADC * 1e-3f) * CAL_GAIN)

/* ── CZT (Chirp Z-Transform) parameters ────────────────────────────────── */
/* The CZT maps SAMPLE_COUNT time-domain samples to SAMPLE_COUNT frequency
 * bins spanning [0, CZT_DELTA_F] Hz with resolution CZT_FREQ_RES.
 * At 10 kHz / 1000 points the Nyquist is 5 kHz, but we only need 0–500 Hz
 * to cover H1(50 Hz) through H10(500 Hz).                                  */
#define CZT_DELTA_F     500.0f                     /* CZT span: 0–500 Hz      */
#define CZT_FREQ_RES    (CZT_DELTA_F / (float)SAMPLE_COUNT)   /* 0.5 Hz/bin  */
/* Angular step between adjacent CZT output bins (radians):
 *   C = π × Δf / (N × fs)   ≈ 1.571e-4 rad                                 */
#define CZT_C           ((float)M_PI * CZT_DELTA_F \
                         / ((float)SAMPLE_COUNT * SAMPLE_RATE))

/* ── Harmonic search ────────────────────────────────────────────────────── */
#define FUNDAMENTAL_HZ  50U    /* Expected mains fundamental frequency (Hz)  */
#define SEARCH_BINS     4U     /* ±4 bins around ideal harmonic bin to track
                                *  small frequency deviations                */

/* ── Zero-crossing hysteresis ───────────────────────────────────────────── */
/* Prevents noise-induced false crossings near the DC bias level.
 * The signal must cross bias ± HYST before a transition is counted.        */
#define ZC_HYST_V       25.0f  /* Voltage channel (ZMPT101B) — ADC counts    */
#define ZC_HYST_I       12.0f  /* Current channel (WCS1700)  — ADC counts    */

/* ── DC bias estimation ─────────────────────────────────────────────────── */
/* The bias is estimated as (avg_of_N_lowest + avg_of_N_highest) / 2.
 * PEAK_AVG_COUNT controls how many extremes are averaged to reduce the
 * impact of individual noise spikes on the bias estimate.                   */
#define PEAK_AVG_COUNT  10

/* ── TX ping-pong UART buffer ───────────────────────────────────────────── */
/* Two buffers allow one frame to be assembled while the previous is being
 * transmitted via interrupt-driven UART, eliminating blocking delays.      */
#define TX_BUF_SIZE     2048U
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
ADC_HandleTypeDef hadc1;
ADC_HandleTypeDef hadc2;
DMA_HandleTypeDef hdma_adc1;

I2C_HandleTypeDef hi2c1;
DMA_HandleTypeDef hdma_i2c1_tx;

UART_HandleTypeDef hlpuart1;

RTC_HandleTypeDef hrtc;

TIM_HandleTypeDef htim1;

/* USER CODE BEGIN PV */
/* ── ADC DMA buffer ─────────────────────────────────────────────────────── */
/* Each 32-bit word stores one simultaneous sample pair:
 *   bits[15: 0] = ADC1 result (voltage)
 *   bits[31:16] = ADC2 result (current)
 * The DMA reads from ADC12_CDR (the dual-mode common data register).       */
static uint32_t  adc_dual_buf[SAMPLE_COUNT];

/* Flag raised by HAL_ADC_ConvCpltCallback; cleared by the main loop.       */
volatile uint8_t capture_done = 0;

/* ── CZT pre-computed twiddle tables ────────────────────────────────────── */
/* tw_n_re[n] = cos(C·n²),  tw_n_im[n] = -sin(C·n²)  for n = 0…N-1.
 * These are the "chirp multiplier" values applied to the input sequence
 * before the convolution step of the CZT.                                  */
static float tw_n_re[SAMPLE_COUNT];
static float tw_n_im[SAMPLE_COUNT];

/* kern_re/im[m] = cos/sin(C·m²) for m = -(N-1)…+(N-1) (length = KERN_LEN).
 * This is the CZT convolution kernel; only the real part differs in sign
 * from tw_n because the kernel uses +sin (conjugate twiddle).              */
static float kern_re[KERN_LEN];
static float kern_im[KERN_LEN];

/* ── Analysis windows ───────────────────────────────────────────────────── */
/* hann_win_v: Hann window for the voltage channel.
 *   Reduces spectral leakage — important for measuring harmonic amplitudes
 *   accurately when the signal frequency is not exactly bin-centred.       */
static float hann_win_v[SAMPLE_COUNT];

/* rect_win_i: Rectangular (unity) window for the current channel.
 *   Preserves waveform amplitude at the cost of higher leakage. Chosen for
 *   the current channel where edge discontinuities are less of a concern
 *   and peak amplitude accuracy matters more.                              */
static float rect_win_i[SAMPLE_COUNT];

/* ── CZT intermediate and output arrays ────────────────────────────────── */
/* g_re / g_im: Input sequence after windowing + twiddle multiplication;
 *   used as the input to the O(N²) direct convolution loop.               */
static float g_re[SAMPLE_COUNT];
static float g_im[SAMPLE_COUNT];

/* czt_mag[k]: Magnitude spectrum in ADC counts for bin k (0–N-1),
 *   covering 0 Hz to CZT_DELTA_F (500 Hz) with 0.5 Hz resolution.        */
static float czt_mag[SAMPLE_COUNT];

/* ── Interrupt-driven UART ping-pong buffers ────────────────────────────── */
/* Two TX buffers allow the assembler (main loop) to write into one buffer
 * while HAL_UART_Transmit_IT() drains the other asynchronously.
 *
 *   tx_write_idx : buffer currently being filled by UART_Print_IT()
 *   tx_read_idx  : buffer currently being transmitted
 *   tx_busy      : non-zero while a HAL UART IT transfer is in progress   */
static uint8_t          tx_buf[2][TX_BUF_SIZE];
static uint16_t         tx_len[2]      = {0, 0};
static uint8_t          tx_write_idx   = 0;
static uint8_t          tx_read_idx    = 0;
static volatile uint8_t tx_busy        = 0;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_ADC1_Init(void);
static void MX_LPUART1_UART_Init(void);
static void MX_TIM1_Init(void);
static void MX_ADC2_Init(void);
static void MX_I2C1_Init(void);
static void MX_RTC_Init(void);
/* USER CODE BEGIN PFP */
static void UART_Print_IT(const char *msg);
static void UART_Flush_IT(void);
void        HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart);
void        HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc);
void        HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef *hi2c);
static int  Find_Peak_Bin(int expected_bin);
static void CZT_Init(void);
static void CZT_Compute_From_Buffer(const float *buf, float bias, const float *win);
static void Compute_CZT_Harmonics_V(float freq);
static void Compute_CZT_Harmonics_I(float freq);
static void Process_Buffer(void);
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* ── OLED I2C Callback ───────────────────────────────────────────────────── */
/**
 * @brief  HAL I2C master TX-complete callback.
 *         Forwards the event to the SSD1306 driver so it can pipeline
 *         the next DMA chunk (multi-page transfers are split internally).
 * @param  hi2c  Pointer to the I2C handle that fired the callback.
 */
void HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    SSD1306_TxCpltCallback(hi2c);
}

/* ── UART_Print_IT ───────────────────────────────────────────────────────── */
/**
 * @brief  Append a null-terminated string to the active write buffer.
 *
 *         This function is non-blocking: it copies the string into the
 *         current ping-pong write buffer. The actual UART transmission is
 *         started only when UART_Flush_IT() is called.
 *
 *         If the string would overflow the buffer (TX_BUF_SIZE bytes) it is
 *         silently discarded to avoid memory corruption.
 *
 * @param  msg  Null-terminated ASCII string to queue.
 */
static void UART_Print_IT(const char *msg)
{
    uint16_t len  = (uint16_t)strlen(msg);
    uint16_t used = tx_len[tx_write_idx];
    if (used + len > TX_BUF_SIZE) return;   /* Drop if buffer would overflow  */
    memcpy(&tx_buf[tx_write_idx][used], msg, len);
    tx_len[tx_write_idx] = used + len;
}

/* ── UART_Flush_IT ───────────────────────────────────────────────────────── */
/**
 * @brief  Commit the current write buffer to the UART TX interrupt engine.
 *
 *         Swaps write and read indices so the filled buffer becomes the
 *         "transmit" buffer and the previously transmitted buffer (now
 *         empty) becomes the new write buffer. If UART is already busy the
 *         new data will be picked up automatically in TxCpltCallback.
 *
 *         Safe to call from the main loop only (not from ISR context).
 */
static void UART_Flush_IT(void)
{
    if (tx_len[tx_write_idx] == 0) return;   /* Nothing to send              */

    if (!tx_busy)
    {
        /* Swap buffers: promote write → read, clear the new write buffer    */
        tx_read_idx          = tx_write_idx;
        tx_write_idx         = tx_write_idx ^ 1U;
        tx_len[tx_write_idx] = 0;
        tx_busy = 1;
        HAL_UART_Transmit_IT(&hlpuart1, tx_buf[tx_read_idx], tx_len[tx_read_idx]);
    }
}

/* ── HAL_UART_TxCpltCallback ─────────────────────────────────────────────── */
/**
 * @brief  UART TX-complete interrupt callback.
 *
 *         Called by HAL when the interrupt-driven UART transfer finishes.
 *         Checks whether the other ping-pong buffer has accumulated data
 *         while transmission was in progress and, if so, starts the next
 *         transfer immediately to avoid gaps.
 *
 * @param  huart  Handle of the UART peripheral that triggered the callback.
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance != LPUART1) return;

    tx_len[tx_read_idx] = 0;   /* Mark just-sent buffer as empty             */

    uint8_t next = tx_read_idx ^ 1U;
    if (tx_len[next] > 0)
    {
        /* Pending data in the other buffer — start transmitting it now      */
        tx_read_idx          = next;
        tx_write_idx         = tx_read_idx ^ 1U;
        tx_len[tx_write_idx] = 0;
        HAL_UART_Transmit_IT(&hlpuart1, tx_buf[tx_read_idx], tx_len[tx_read_idx]);
    }
    else
    {
        tx_busy = 0;   /* No pending data; UART is now idle                  */
    }
}

/* ── HAL_ADC_ConvCpltCallback ────────────────────────────────────────────── */
/**
 * @brief  DMA transfer-complete callback for the dual ADC.
 *
 *         Called when DMA1 has filled all SAMPLE_COUNT words of adc_dual_buf.
 *         Sets the capture_done flag so the main loop can call Process_Buffer().
 *
 *         Heavy processing is intentionally deferred to the main loop to
 *         avoid blocking the ISR and starving other interrupts.
 *
 * @param  hadc  Pointer to the ADC handle (checked to be ADC1/master).
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        /* Simply raise flag. Array processing is offloaded to main loop to stop ISR choke */
        capture_done = 1;
    }
}

/* ── Find_Peak_Bin ───────────────────────────────────────────────────────── */
/**
 * @brief  Locate the CZT magnitude peak near an expected harmonic bin.
 *
 *         Searches the czt_mag[] array within ±SEARCH_BINS of expected_bin
 *         and returns the index of the largest magnitude value. This
 *         compensates for small mains frequency deviations (e.g. 49.8 Hz
 *         instead of exactly 50 Hz) without requiring a PLL.
 *
 * @param  expected_bin  Ideal bin index for this harmonic (= f_h / CZT_FREQ_RES).
 * @return Index of the highest-magnitude bin in the search window.
 */
static int Find_Peak_Bin(int expected_bin)
{
    int start = expected_bin - (int)SEARCH_BINS;
    int end   = expected_bin + (int)SEARCH_BINS;
    if (start < 0)                start = 0;
    if (end >= (int)SAMPLE_COUNT) end   = (int)SAMPLE_COUNT - 1;

    int   peak_bin = expected_bin;
    float peak_val = 0.0f;
    for (int k = start; k <= end; k++)
        if (czt_mag[k] > peak_val) { peak_val = czt_mag[k]; peak_bin = k; }
    return peak_bin;
}

/* ── CZT_Init ────────────────────────────────────────────────────────────── */
/**
 * @brief  Pre-compute all fixed CZT tables and window coefficients.
 *
 *         Must be called once during initialisation before any call to
 *         CZT_Compute_From_Buffer(). Populates:
 *
 *           hann_win_v[n]  = 0.5·(1 − cos(2π·n/N))   Hann window
 *           rect_win_i[n]  = 1.0                       Rectangular window
 *           tw_n_re/im[n]  = exp(−j·C·n²)              Input twiddle factors
 *           kern_re/im[m]  = exp(+j·C·m²)              Kernel (m = −N+1…N−1)
 *
 *         where C = π·Δf / (N·fs).
 */
static void CZT_Init(void)
{
    const float C   = CZT_C;
    const float pi2 = 2.0f * (float)M_PI;

    for (uint32_t n = 0; n < SAMPLE_COUNT; n++)
    {
        /* Hann window: reduces spectral leakage for voltage analysis        */
        hann_win_v[n] = 0.5f * (1.0f - cosf(pi2 * (float)n / (float)SAMPLE_COUNT));

        /* Rectangular window: unity weights, no leakage suppression         */
        rect_win_i[n] = 1.0f;

        /* Input chirp twiddle: tw[n] = exp(−jCn²)                          */
        float angle  = C * (float)(n * n);
        tw_n_re[n]   =  cosf(angle);
        tw_n_im[n]   = -sinf(angle);
    }

    /* Kernel chirp: kern[m] = exp(+jCm²) for m = -(N-1) … +(N-1).
     * Index mapping: kern_re/im[m + (N-1)] stores the value for offset m.  */
    for (int32_t m = -(int32_t)(SAMPLE_COUNT - 1U); m <=  (int32_t)(SAMPLE_COUNT - 1U); m++)
    {
        float    angle = C * (float)(m * m);
        uint32_t idx   = (uint32_t)(m + (int32_t)(SAMPLE_COUNT - 1U));
        kern_re[idx]   =  cosf(angle);
        kern_im[idx]   =  sinf(angle);
    }
}

/* ── CZT_Compute_From_Buffer ─────────────────────────────────────────────── */
/**
 * @brief  Compute the Chirp Z-Transform magnitude spectrum from a raw buffer.
 *
 *         Implements Bluestein's (chirp-z) algorithm in three steps:
 *
 *         Step 1 — Window + twiddle multiply:
 *           g[n] = win[n] · (buf[n] − bias) · exp(−jCn²)
 *
 *         Step 2 — Direct O(N²) convolution with the kernel exp(+jCm²):
 *           G[k] = Σ_{n=0}^{N-1}  g[n] · kern[N−1+k−n]
 *
 *         Step 3 — Output twiddle multiply + magnitude:
 *           X[k] = G[k] · exp(−jCk²)
 *           czt_mag[k] = (2/N) · |X[k]|
 *
 *         The factor 2/N normalises the single-sided spectrum so that each
 *         bin directly represents the peak sinusoidal amplitude in the
 *         same units as the input (ADC counts after bias removal).
 *
 * @param  buf   Pointer to SAMPLE_COUNT float samples (raw ADC counts).
 * @param  bias  DC offset to subtract before processing (ADC counts).
 * @param  win   Pointer to the SAMPLE_COUNT-length window array.
 *
 * @note   Result is written to the module-global czt_mag[] array.
 *         This function takes ~40 ms at 170 MHz for N=1000 (O(N²)).
 */
static void CZT_Compute_From_Buffer(const float *buf, float bias, const float *win)
{
    const float scale = 2.0f / (float)SAMPLE_COUNT;

    /* Step 1: Window, remove DC bias, apply input chirp twiddle             */
    for (uint32_t n = 0; n < SAMPLE_COUNT; n++)
    {
        float xn = win[n] * (buf[n] - bias);   /* windowed, DC-removed sample */
        g_re[n]  = xn * tw_n_re[n];
        g_im[n]  = xn * tw_n_im[n];
    }

    /* Step 2: Direct convolution; Step 3: Output twiddle + magnitude        */
    for (uint32_t k = 0; k < SAMPLE_COUNT; k++)
    {
        float acc_re = 0.0f, acc_im = 0.0f;

        /* Convolve g[] with the chirp kernel at output bin k                */
        for (uint32_t n = 0; n < SAMPLE_COUNT; n++)
        {
            uint32_t kidx = (SAMPLE_COUNT - 1U) + k - n;   /* kernel index   */
            float    kr_n = kern_re[kidx];
            float    ki_n = kern_im[kidx];
            /* Complex multiply-accumulate: (g_re + j·g_im)(kr + j·ki)      */
            acc_re += g_re[n] * kr_n - g_im[n] * ki_n;
            acc_im += g_re[n] * ki_n + g_im[n] * kr_n;
        }

        /* Apply output twiddle exp(−jCk²) and compute magnitude             */
        float xfin_re = acc_re * tw_n_re[k] - acc_im * tw_n_im[k];
        float xfin_im = acc_re * tw_n_im[k] + acc_im * tw_n_re[k];
        czt_mag[k]    = scale * sqrtf(xfin_re * xfin_re + xfin_im * xfin_im);
    }
}

/* ── Compute_CZT_Harmonics_V ─────────────────────────────────────────────── */
/**
 * @brief  Read harmonic amplitudes from czt_mag[] and report voltage THD.
 *
 *         For each harmonic H1…H10 (50 Hz, 100 Hz, … 500 Hz):
 *           1. Compute the ideal CZT bin index  k = round(h·50 / 0.5)
 *           2. Call Find_Peak_Bin() to track small frequency deviations
 *           3. Convert peak magnitude from ADC counts to true RMS volts:
 *              V_peak[h] = czt_mag[k_peak] × (Vref / ADC_RES) × CAL_FACTOR_V
 *           4. Accumulate Σ(V²) for harmonics H2–H10
 *
 *         THD(%) = 100 × sqrt(ΣH2…H10 V²) / V_H1
 *
 *         Results are printed to the UART write buffer via UART_Print_IT().
 *
 * @param  freq  Measured fundamental frequency (Hz) for the header line.
 *
 * @note   Assumes CZT_Compute_From_Buffer() has already been called for the
 *         voltage channel so that czt_mag[] is populated.
 */
static void Compute_CZT_Harmonics_V(float freq)
{
    float amplitudes[NUM_HARMONICS];
    float sum_sq_h = 0.0f;          /* Accumulates Σ(V_h²) for h = 2…10    */

    /* Print channel header with measured fundamental and frequency resolution */
    {
        char hdr[80];
        snprintf(hdr, sizeof(hdr),
                 "[V] CZT Harmonics (fund=%.2fHz  fR=%.4fHz)\r\n",
                 (double)freq, (double)CZT_FREQ_RES);
        UART_Print_IT(hdr);
    }

    for (uint8_t h = 1; h <= NUM_HARMONICS; h++)
    {
        float f_h     = (float)(h * FUNDAMENTAL_HZ);               /* Target frequency    */
        int   k_ideal = (int)(f_h / CZT_FREQ_RES + 0.5f);          /* Nearest ideal bin   */
        int   k_peak  = Find_Peak_Bin(k_ideal);                     /* Best actual bin     */

        /* Convert CZT magnitude (ADC counts peak) → volts peak → note: czt_mag
         * is already scaled by 2/N so it represents peak amplitude directly */
        float amp_v   = czt_mag[k_peak] * (VREF / ADC_RES) * CAL_FACTOR_V;

        amplitudes[h - 1] = amp_v;
        if (h > 1) sum_sq_h = fmaf(amp_v, amp_v, sum_sq_h);   /* Sum harmonic power */

        char line[64];
        snprintf(line, sizeof(line), "H%02u (%4uHz): %7.4fV  [bin %3d]\r\n",
                 (unsigned)h, (unsigned)(h * FUNDAMENTAL_HZ), (double)amp_v, k_peak);
        UART_Print_IT(line);
    }

    /* THD = 100% × √(Σ H2-H10 amplitudes²) / H1 amplitude                  */
    float h1  = amplitudes[0];
    float thd = (h1 > 1e-9f) ? (100.0f * sqrtf(sum_sq_h) / h1) : 0.0f;

    char thd_line[48];
    snprintf(thd_line, sizeof(thd_line), "THD: %6.2f%%\r\n\r\n", (double)thd);
    UART_Print_IT(thd_line);
}

/* ── Compute_CZT_Harmonics_I ─────────────────────────────────────────────── */
/**
 * @brief  Read harmonic amplitudes from czt_mag[] and report current THD.
 *
 *         Identical harmonic search logic to Compute_CZT_Harmonics_V() but
 *         converts magnitudes to amperes (RMS) using COUNTS_TO_AMPS() and
 *         divides by √2 to obtain the RMS value of each sinusoidal component.
 *
 *         For each harmonic H1…H10:
 *           I_rms[h] = COUNTS_TO_AMPS(czt_mag[k_peak]) / √2
 *
 *         THD(%) = 100 × sqrt(ΣH2…H10 I_rms²) / I_rms_H1
 *
 * @param  freq  Measured fundamental frequency (Hz) for the header line.
 *
 * @note   Assumes CZT_Compute_From_Buffer() has been called for the current
 *         channel (rectangular window) and czt_mag[] is freshly populated.
 */
static void Compute_CZT_Harmonics_I(float freq)
{
    float amplitudes_a[NUM_HARMONICS];
    float sum_sq_h = 0.0f;          /* Accumulates Σ(I_rms_h²) for h = 2…10 */

    {
        char hdr[80];
        snprintf(hdr, sizeof(hdr),
                 "[I] CZT Harmonics (fund=%.2fHz  fR=%.4fHz)\r\n",
                 (double)freq, (double)CZT_FREQ_RES);
        UART_Print_IT(hdr);
    }

    for (uint8_t h = 1; h <= NUM_HARMONICS; h++)
    {
        float f_h     = (float)(h * FUNDAMENTAL_HZ);
        int   k_ideal = (int)(f_h / CZT_FREQ_RES + 0.5f);
        int   k_peak  = Find_Peak_Bin(k_ideal);

        /* czt_mag gives peak amplitude in ADC counts → convert to A peak
         * → divide by √2 to get RMS for a pure sinusoid                    */
        float amp_arms = COUNTS_TO_AMPS(czt_mag[k_peak]) / 1.4142136f;

        amplitudes_a[h - 1] = amp_arms;
        if (h > 1) sum_sq_h = fmaf(amp_arms, amp_arms, sum_sq_h);

        char line[72];
        snprintf(line, sizeof(line), "H%02u (%4uHz): %7.4fA rms  [bin %3d]\r\n",
                 (unsigned)h, (unsigned)(h * FUNDAMENTAL_HZ), (double)amp_arms, k_peak);
        UART_Print_IT(line);
    }

    float h1  = amplitudes_a[0];
    float thd = (h1 > 1e-6f) ? (100.0f * sqrtf(sum_sq_h) / h1) : 0.0f;

    char thd_line[48];
    snprintf(thd_line, sizeof(thd_line), "THD: %6.2f%%\r\n\r\n", (double)thd);
    UART_Print_IT(thd_line);
}

/* ── Process_Buffer ──────────────────────────────────────────────────────── */
/**
 * @brief  Main per-frame processing routine — called from the main loop
 *         every time capture_done is raised by the DMA callback.
 *
 *         Processing sequence:
 *
 *         1. SNAPSHOT & SPLIT
 *            Unpack the 32-bit dual-ADC DMA words into separate float arrays
 *            local_v[] (ADC1, voltage) and local_i[] (ADC2, current).
 *
 *         2. VOLTAGE CHANNEL
 *            a. DC bias  — estimated as average of the N lowest and N highest
 *                          samples (PEAK_AVG_COUNT = 10); robust against a few
 *                          outliers.
 *            b. VRMS     — sqrt( Σ(v−bias)² / N ) × (Vref/ADC_RES) × CAL_FACTOR_V
 *            c. Frequency — zero-crossing rate with hysteresis (ZC_HYST_V);
 *                           falls back to FUNDAMENTAL_HZ if no crossings.
 *            d. CZT      — Hann-windowed spectrum; harmonic report + THD.
 *
 *         3. CURRENT CHANNEL
 *            Same structure as voltage but uses COUNTS_TO_AMPS() for
 *            unit conversion and the rectangular window for CZT.
 *            Also prints diagnostic voltages (V_adc, V_sens, V0G_cal) to
 *            assist calibration verification.
 *
 *         4. POWER & POWER FACTOR
 *            Active power P = (1/N) Σ v_inst·i_inst  (instantaneous product)
 *            Apparent power S = Vrms × Irms
 *            Power factor PF = P / S    (clamped to [-1, 1])
 *            Phase angle φ = arccos(PF) in degrees
 *
 *         5. OLED UPDATE
 *            Displays Vrms, Irms, Active Power and PF on the SSD1306 screen
 *            (only if SSD1306_IsReady() is true — skipped during I2C DMA).
 *
 *         6. UART FLUSH
 *            Calls UART_Flush_IT() once to transmit the assembled frame.
 *
 *         7. RE-ARM DMA
 *            Clears any ADC overrun flags and restarts the dual DMA capture
 *            so the next frame begins accumulating immediately.
 *
 * @note   local_v and local_i are declared static to avoid allocating
 *         2 × SAMPLE_COUNT × 4 bytes (8 kB) on the call stack each frame.
 */
static void Process_Buffer(void)
{
    static float local_v[SAMPLE_COUNT];   /* voltage samples (float)          */
    static float local_i[SAMPLE_COUNT];   /* current samples (float)          */

    float bias_v = 0.0f, vrms = 0.0f;
    float bias_i = 0.0f, irms = 0.0f;

    /* ── 1. Snapshot and Split both channels instantly ── */
    /* Unpack the DMA buffer: each 32-bit word = {ADC2[31:16], ADC1[15:0]}   */
    for (uint32_t n = 0; n < SAMPLE_COUNT; n++)
    {
        local_v[n] = (float)(adc_dual_buf[n] & 0x0000FFFFU);         /* ADC1 */
        local_i[n] = (float)((adc_dual_buf[n] >> 16) & 0x0000FFFFU); /* ADC2 */
    }

    /* ================================================================
     * VOLTAGE CHANNEL
     * ============================================================== */
    {
        /* ── 2a. DC Bias estimation (rolling extremes method) ── */
        /* Maintain two small arrays tracking the N lowest and N highest
         * samples. After a full scan:
         *   bias = (mean_of_N_lowest + mean_of_N_highest) / 2
         * This is more robust than a simple mean when the captured frame
         * doesn't contain an integer number of complete cycles.              */
        float low_vals[PEAK_AVG_COUNT], high_vals[PEAK_AVG_COUNT];
        for (int j = 0; j < PEAK_AVG_COUNT; j++) low_vals[j] = high_vals[j] = local_v[j];

        float low_max = low_vals[0], high_min = high_vals[0];
        int   low_max_idx = 0, high_min_idx = 0;
        for (int j = 1; j < PEAK_AVG_COUNT; j++)
        {
            if (low_vals[j]  > low_max)  { low_max  = low_vals[j];  low_max_idx  = j; }
            if (high_vals[j] < high_min) { high_min = high_vals[j]; high_min_idx = j; }
        }

        for (uint32_t i = PEAK_AVG_COUNT; i < SAMPLE_COUNT; i++)
        {
            float s = local_v[i];
            /* Keep the N lowest: replace current maximum in low_vals if s is smaller */
            if (s < low_max)
            {
                low_vals[low_max_idx] = s; low_max = low_vals[0]; low_max_idx = 0;
                for (int j = 1; j < PEAK_AVG_COUNT; j++)
                    if (low_vals[j] > low_max) { low_max = low_vals[j]; low_max_idx = j; }
            }
            /* Keep the N highest: replace current minimum in high_vals if s is larger */
            if (s > high_min)
            {
                high_vals[high_min_idx] = s; high_min = high_vals[0]; high_min_idx = 0;
                for (int j = 1; j < PEAK_AVG_COUNT; j++)
                    if (high_vals[j] < high_min) { high_min = high_vals[j]; high_min_idx = j; }
            }
        }

        float low_avg_v = 0.0f, high_avg_v = 0.0f;
        for (int j = 0; j < PEAK_AVG_COUNT; j++) { low_avg_v += low_vals[j]; high_avg_v += high_vals[j]; }
        low_avg_v  /= (float)PEAK_AVG_COUNT;
        high_avg_v /= (float)PEAK_AVG_COUNT;

        bias_v  = (low_avg_v + high_avg_v) / 2.0f;  /* DC midpoint estimate  */
        uint16_t min_v   = (uint16_t)low_avg_v;
        uint16_t max_v   = (uint16_t)high_avg_v;

        /* ── 2b. VRMS ── */
        /* Compute RMS over the full frame using double precision accumulator
         * to minimise floating-point rounding for large count sums.         */
        double sum_sq_v = 0.0;
        for (uint32_t i = 0; i < SAMPLE_COUNT; i++)
        {
            double raw = (double)(local_v[i] - bias_v);
            sum_sq_v  += raw * raw;
        }
        float rms_counts_v = sqrtf((float)(sum_sq_v / (double)SAMPLE_COUNT));
        vrms               = rms_counts_v * (VREF / ADC_RES) * CAL_FACTOR_V;

        /* ── 2c. Zero-crossing frequency (voltage) ── */
        /* Count positive-going zero crossings using a hysteresis band to
         * suppress noise-induced false triggers near the DC bias.           */
        float zc_high_v = bias_v + ZC_HYST_V;
        float zc_low_v  = bias_v - ZC_HYST_V;
        int   crossings_v = 0;
        int   prev_sign_v = (local_v[0] > zc_high_v) ?  1 : (local_v[0] < zc_low_v)  ? -1 : 0;
        for (uint32_t i = 1; i < SAMPLE_COUNT; i++)
        {
            int cur;
            if      (local_v[i] > zc_high_v) cur =  1;
            else if (local_v[i] < zc_low_v)  cur = -1;
            else                             cur =  prev_sign_v;   /* inside hysteresis band */
            if (prev_sign_v == -1 && cur == 1) crossings_v++;      /* rising edge detected  */
            prev_sign_v = cur;
        }
        /* freq = (positive crossings / frame) × sample_rate
         * = number of complete cycles per second = fundamental frequency     */
        float freq_v = (crossings_v > 0)
                     ? ((float)crossings_v * SAMPLE_RATE / (float)SAMPLE_COUNT)
                     : (float)FUNDAMENTAL_HZ;   /* Fallback if no crossings found */

        /* Print voltage summary line */
        {
            char msg[128];
            snprintf(msg, sizeof(msg),
                     "[V] Min:%4u Max:%4u Pk-Pk:%4u Bias:%.1f Freq:%.2fHz VRMS:%.4fV\r\n",
                     (unsigned)min_v, (unsigned)max_v, (unsigned)(max_v - min_v),
                     (double)bias_v, (double)freq_v, (double)vrms);
            UART_Print_IT(msg);
        }

        /* ── 2d. CZT + harmonic report ── */
        CZT_Compute_From_Buffer(local_v, bias_v, hann_win_v);
        Compute_CZT_Harmonics_V(freq_v);
    }

    /* ================================================================
     * CURRENT CHANNEL
     * ============================================================== */
    {
        /* Same peak-averaging bias estimator as the voltage channel         */
        float low_vals[PEAK_AVG_COUNT], high_vals[PEAK_AVG_COUNT];
        for (int j = 0; j < PEAK_AVG_COUNT; j++) low_vals[j] = high_vals[j] = local_i[j];

        float low_max = low_vals[0], high_min = high_vals[0];
        int   low_max_idx = 0, high_min_idx = 0;
        for (int j = 1; j < PEAK_AVG_COUNT; j++)
        {
            if (low_vals[j]  > low_max)  { low_max  = low_vals[j];  low_max_idx  = j; }
            if (high_vals[j] < high_min) { high_min = high_vals[j]; high_min_idx = j; }
        }

        for (uint32_t i = PEAK_AVG_COUNT; i < SAMPLE_COUNT; i++)
        {
            float s = local_i[i];
            if (s < low_max)
            {
                low_vals[low_max_idx] = s; low_max = low_vals[0]; low_max_idx = 0;
                for (int j = 1; j < PEAK_AVG_COUNT; j++)
                    if (low_vals[j] > low_max) { low_max = low_vals[j]; low_max_idx = j; }
            }
            if (s > high_min)
            {
                high_vals[high_min_idx] = s; high_min = high_vals[0]; high_min_idx = 0;
                for (int j = 1; j < PEAK_AVG_COUNT; j++)
                    if (high_vals[j] < high_min) { high_min = high_vals[j]; high_min_idx = j; }
            }
        }

        float low_avg_i = 0.0f, high_avg_i = 0.0f;
        for (int j = 0; j < PEAK_AVG_COUNT; j++) { low_avg_i += low_vals[j]; high_avg_i += high_vals[j]; }
        low_avg_i  /= (float)PEAK_AVG_COUNT;
        high_avg_i /= (float)PEAK_AVG_COUNT;

        bias_i  = (low_avg_i + high_avg_i) / 2.0f;
        uint16_t min_i   = (uint16_t)low_avg_i;
        uint16_t max_i   = (uint16_t)high_avg_i;

        /* ── IRMS ── */
        double sum_sq_i = 0.0;
        for (uint32_t i = 0; i < SAMPLE_COUNT; i++)
        {
            double raw = (double)(local_i[i] - bias_i);
            sum_sq_i  += raw * raw;
        }
        float rms_counts_i = sqrtf((float)(sum_sq_i / (double)SAMPLE_COUNT));
        irms               = COUNTS_TO_AMPS(rms_counts_i);   /* RMS amperes   */

        /* Diagnostic voltages for calibration verification:
         *   v_adc_bias   = bias ADC count → voltage at the ADC pin
         *   v_sens_bias  = voltage at the sensor output (before divider)
         *   v0g_expected = V0G derived from the stored calibration count     */
        float v_adc_bias   = bias_i       * (VREF / ADC_RES);
        float v_sens_bias  = v_adc_bias   / DIVIDER_RATIO;
        float v0g_expected = V0G_COUNTS_CAL * (VREF / ADC_RES);

        /* ── Zero-crossing frequency (current) ── */
        float zc_high_i = bias_i + ZC_HYST_I;
        float zc_low_i  = bias_i - ZC_HYST_I;
        int   crossings_i = 0;
        int   prev_sign_i = (local_i[0] > zc_high_i) ?  1 : (local_i[0] < zc_low_i)  ? -1 : 0;
        for (uint32_t i = 0; i < SAMPLE_COUNT; i++)
        {
            int cur;
            if      (local_i[i] > zc_high_i) cur =  1;
            else if (local_i[i] < zc_low_i)  cur = -1;
            else                             cur =  prev_sign_i;
            if (prev_sign_i == -1 && cur == 1) crossings_i++;
            prev_sign_i = cur;
        }
        float freq_i = (crossings_i > 0)
                     ? ((float)crossings_i * SAMPLE_RATE / (float)SAMPLE_COUNT)
                     : (float)FUNDAMENTAL_HZ;

        /* Print current summary line (includes calibration diagnostics)     */
        {
            char msg[192];
            snprintf(msg, sizeof(msg),
                     "[I] Bias:%4u | V_adc=%.3fV V_sens=%.3fV V0G_cal=%.3fV | "
                     "PkPk:%4u | Freq:%.2fHz | IRMS:%.4fA\r\n",
                     (unsigned)(uint16_t)bias_i, (double)v_adc_bias, (double)v_sens_bias,
                     (double)v0g_expected, (unsigned)(max_i - min_i), (double)freq_i, (double)irms);
            UART_Print_IT(msg);
        }

        /* ── CZT + harmonic report (rectangular window) ── */
        CZT_Compute_From_Buffer(local_i, bias_i, rect_win_i);
        Compute_CZT_Harmonics_I(freq_i);
    }

    /* ================================================================
     * TOTAL POWER & PHASE ANGLE CALCULATION
     * ============================================================== */
    {
        /* Active (real) power via instantaneous power averaging:
         *   P = (1/N) Σ_{i=0}^{N-1}  v_inst[i] · i_inst[i]
         * This is the true fundamental + all-harmonic active power.         */
        double sum_p = 0.0;

        for (uint32_t i = 0; i < SAMPLE_COUNT; i++)
        {
            /* Convert each raw ADC count (bias-removed) to physical units   */
            float v_inst = (local_v[i] - bias_v) * (VREF / ADC_RES) * CAL_FACTOR_V;
            float i_inst = COUNTS_TO_AMPS(local_i[i] - bias_i);
            sum_p += (double)(v_inst * i_inst);
        }

        float active_power   = (float)(sum_p / (double)SAMPLE_COUNT);   /* Watts */
        float apparent_power = vrms * irms;                              /* VA    */

        float power_factor    = 0.0f;
        float phase_angle_deg = 0.0f;

        if (apparent_power > 0.001f)
        {
            power_factor = active_power / apparent_power;

            /* Clamp to [-1, 1] to guard against small floating-point overshoots
             * that would make acosf() return NaN                             */
            if (power_factor > 1.0f) power_factor = 1.0f;
            else if (power_factor < -1.0f) power_factor = -1.0f;

            /* φ = arccos(PF) — displacement angle between V and I fundamentals */
            phase_angle_deg = acosf(power_factor) * 180.0f / (float)M_PI;
        }

        char pwr_msg[128];
        snprintf(pwr_msg, sizeof(pwr_msg),
                 "[PWR] Active: %7.2f W | Apparent: %7.2f VA | PF: %5.3f | Phase: %5.1f deg\r\n",
                 (double)active_power, (double)apparent_power,
                 (double)power_factor, (double)phase_angle_deg);
        UART_Print_IT(pwr_msg);

        /* ================================================================
         * OLED DISPLAY UPDATE
         * ============================================================== */
        /* Only update the display if the SSD1306 I2C DMA is idle.
         * SSD1306_IsReady() returns false while a previous frame transfer
         * is still in progress, preventing I2C bus contention.             */
        if (SSD1306_IsReady())
        {
            char oled_v[32];
            char oled_i[32];
            char oled_p[32];
            char oled_pf[32];

            snprintf(oled_v,  sizeof(oled_v),  "Vrms : %.1f V", (double)vrms);
            snprintf(oled_i,  sizeof(oled_i),  "Irms : %.2f A", (double)irms);
            snprintf(oled_p,  sizeof(oled_p),  "Power: %.1f W", (double)active_power);
            snprintf(oled_pf, sizeof(oled_pf), "PF   : %.2f",   (double)power_factor);

            SSD1306_Clear();

            /* Page 0: Title */
            SSD1306_WriteString(0, 0, "-- Power Monitor --");

            /* Pages 2 & 3: Voltage and Current */
            SSD1306_WriteString(0, 2, oled_v);
            SSD1306_WriteString(0, 3, oled_i);

            /* Pages 5 & 6: Power and Power Factor */
            SSD1306_WriteString(0, 5, oled_p);
            SSD1306_WriteString(0, 6, oled_pf);

            SSD1306_UpdateScreen();
        }
    }

    /* Single flush — kicks off IT transfer for the whole assembled frame    */
    UART_Print_IT("----------------------------------------\r\n");
    UART_Flush_IT();

    /* ── FIX: Clear Hardware Overrun flags before re-arming ── */
    /* ADC overrun (OVR) occurs when a new conversion completes before the
     * previous result was read. Clearing OVR here prevents the next DMA
     * capture from being suppressed by a stale overrun condition.           */
    __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_OVR);
    __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_OVR);

    /* ── Re-arm DMA ── */
    /* Restart dual simultaneous ADC DMA capture for the next frame.
     * TIM1 TRGO continues running so conversion timing is uninterrupted.   */
    HAL_ADCEx_MultiModeStart_DMA(&hadc1, (uint32_t *)adc_dual_buf, SAMPLE_COUNT);
}

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_ADC1_Init();
  MX_LPUART1_UART_Init();
  MX_TIM1_Init();
  MX_ADC2_Init();
  MX_I2C1_Init();
  MX_RTC_Init();
  /* USER CODE BEGIN 2 */

    /* ── OLED splash screen ── */
    SSD1306_Init(&hi2c1);
    SSD1306_Clear();
    SSD1306_WriteString(0, 0, "Booting...");
    SSD1306_UpdateScreen();
    HAL_Delay(500);   /* Allow OLED DMA transfer to complete before continuing */

    /* ── Pre-compute CZT tables once ── */
    CZT_Init();

    /* ── ADC self-calibration ── */
    /* HAL calibration removes internal offset errors from the ADC hardware.
     * Must be run before the first conversion and after each power-on.     */
    HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED);
    HAL_ADCEx_Calibration_Start(&hadc2, ADC_SINGLE_ENDED);

    /* ── Startup UART banner ── */
    UART_Print_IT("\r\n=== CZT Simultaneous V+I Harmonic Analyser (G474RE) ===\r\n");
    UART_Print_IT("[V] ZMPT101B 5V + 10k/10k divider -> PA0  (ADC1_IN1)\r\n");
    UART_Print_IT("[I] WCS1700  5V + 10k/10k divider -> PA6  (ADC2_IN3)\r\n");
    UART_Print_IT("fs=10kHz  N=1000  Df=500Hz  fR=0.5Hz\r\n");
    UART_Print_IT("Dual Regular Simultaneous mode, TIM1 TRGO trigger\r\n");
    UART_Print_IT("H1(50Hz)..H10(500Hz) + THD  per channel\r\n");
    UART_Print_IT("-------------------------------------------------------\r\n");
    UART_Flush_IT();

    /* ── Start dual ADC DMA capture ── */
    /* HAL_ADCEx_MultiModeStart_DMA arms the DMA and enables both ADCs.
     * TIM1 TRGO events pace conversions at SAMPLE_RATE (10 kHz).          */
    /* Start dual ADC — DMA reads ADC12_CDR (32-bit interleaved words)      */
    HAL_ADCEx_MultiModeStart_DMA(&hadc1, (uint32_t *)adc_dual_buf, SAMPLE_COUNT);
    HAL_TIM_Base_Start(&htim1);
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    /* Poll the flag set by HAL_ADC_ConvCpltCallback.
     * When set, the DMA has filled adc_dual_buf with SAMPLE_COUNT samples.
     * Clear immediately so a new capture can begin inside Process_Buffer().  */
    if (capture_done)
    {
        capture_done = 0;
        HAL_GPIO_TogglePin(LD2_GPIO_Port, LD2_Pin); /* Heartbeat LED toggle */
        Process_Buffer();
    }
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_LSI|RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV6;
  RCC_OscInitStruct.PLL.PLLN = 85;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief ADC1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC1_Init(void)
{

  /* USER CODE BEGIN ADC1_Init 0 */

  /* USER CODE END ADC1_Init 0 */

  ADC_MultiModeTypeDef multimode = {0};
  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC1_Init 1 */

  /* USER CODE END ADC1_Init 1 */

  /** Common config
  */
  hadc1.Instance = ADC1;
  hadc1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
  hadc1.Init.Resolution = ADC_RESOLUTION_12B;
  hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc1.Init.GainCompensation = 0;
  hadc1.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc1.Init.LowPowerAutoWait = DISABLE;
  hadc1.Init.ContinuousConvMode = DISABLE;
  hadc1.Init.NbrOfConversion = 1;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.ExternalTrigConv = ADC_EXTERNALTRIG_T1_TRGO;
  hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_RISING;
  hadc1.Init.DMAContinuousRequests = ENABLE;
  hadc1.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  hadc1.Init.OversamplingMode = DISABLE;
  if (HAL_ADC_Init(&hadc1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure the ADC multi-mode
  */
  multimode.Mode = ADC_DUALMODE_REGSIMULT;
  multimode.DMAAccessMode = ADC_DMAACCESSMODE_12_10_BITS;
  multimode.TwoSamplingDelay = ADC_TWOSAMPLINGDELAY_1CYCLE;
  if (HAL_ADCEx_MultiModeConfigChannel(&hadc1, &multimode) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_1;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_24CYCLES_5;
  sConfig.SingleDiff = ADC_SINGLE_ENDED;
  sConfig.OffsetNumber = ADC_OFFSET_NONE;
  sConfig.Offset = 0;
  if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC1_Init 2 */

  /* USER CODE END ADC1_Init 2 */

}

/**
  * @brief ADC2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC2_Init(void)
{

  /* USER CODE BEGIN ADC2_Init 0 */

  /* USER CODE END ADC2_Init 0 */

  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC2_Init 1 */

  /* USER CODE END ADC2_Init 1 */

  /** Common config
  */
  hadc2.Instance = ADC2;
  hadc2.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
  hadc2.Init.Resolution = ADC_RESOLUTION_12B;
  hadc2.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc2.Init.GainCompensation = 0;
  hadc2.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc2.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc2.Init.LowPowerAutoWait = DISABLE;
  hadc2.Init.ContinuousConvMode = DISABLE;
  hadc2.Init.NbrOfConversion = 1;
  hadc2.Init.DiscontinuousConvMode = DISABLE;
  hadc2.Init.DMAContinuousRequests = DISABLE;
  hadc2.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  hadc2.Init.OversamplingMode = DISABLE;
  if (HAL_ADC_Init(&hadc2) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_6;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_24CYCLES_5;
  sConfig.SingleDiff = ADC_SINGLE_ENDED;
  sConfig.OffsetNumber = ADC_OFFSET_NONE;
  sConfig.Offset = 0;
  if (HAL_ADC_ConfigChannel(&hadc2, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC2_Init 2 */

  /* USER CODE END ADC2_Init 2 */

}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.Timing = 0x40B285C2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Analogue filter
  */
  if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Digital filter
  */
  if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief LPUART1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_LPUART1_UART_Init(void)
{

  /* USER CODE BEGIN LPUART1_Init 0 */

  /* USER CODE END LPUART1_Init 0 */

  /* USER CODE BEGIN LPUART1_Init 1 */

  /* USER CODE END LPUART1_Init 1 */
  hlpuart1.Instance = LPUART1;
  hlpuart1.Init.BaudRate = 209700;
  hlpuart1.Init.WordLength = UART_WORDLENGTH_8B;
  hlpuart1.Init.StopBits = UART_STOPBITS_1;
  hlpuart1.Init.Parity = UART_PARITY_NONE;
  hlpuart1.Init.Mode = UART_MODE_TX_RX;
  hlpuart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  hlpuart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  hlpuart1.Init.ClockPrescaler = UART_PRESCALER_DIV1;
  hlpuart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&hlpuart1) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetTxFifoThreshold(&hlpuart1, UART_TXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetRxFifoThreshold(&hlpuart1, UART_RXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_DisableFifoMode(&hlpuart1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN LPUART1_Init 2 */

  /* USER CODE END LPUART1_Init 2 */

}

/**
  * @brief RTC Initialization Function
  * @param None
  * @retval None
  */
static void MX_RTC_Init(void)
{

  /* USER CODE BEGIN RTC_Init 0 */

  /* USER CODE END RTC_Init 0 */

  RTC_TimeTypeDef sTime = {0};
  RTC_DateTypeDef sDate = {0};

  /* USER CODE BEGIN RTC_Init 1 */

  /* USER CODE END RTC_Init 1 */

  /** Initialize RTC Only
  */
  hrtc.Instance = RTC;
  hrtc.Init.HourFormat = RTC_HOURFORMAT_24;
  hrtc.Init.AsynchPrediv = 127;
  hrtc.Init.SynchPrediv = 255;
  hrtc.Init.OutPut = RTC_OUTPUT_DISABLE;
  hrtc.Init.OutPutRemap = RTC_OUTPUT_REMAP_NONE;
  hrtc.Init.OutPutPolarity = RTC_OUTPUT_POLARITY_HIGH;
  hrtc.Init.OutPutType = RTC_OUTPUT_TYPE_OPENDRAIN;
  hrtc.Init.OutPutPullUp = RTC_OUTPUT_PULLUP_NONE;
  if (HAL_RTC_Init(&hrtc) != HAL_OK)
  {
    Error_Handler();
  }

  /* USER CODE BEGIN Check_RTC_BKUP */

  /* USER CODE END Check_RTC_BKUP */

  /** Initialize RTC and set the Time and Date
  */
  sTime.Hours = 2;
  sTime.Minutes = 10;
  sTime.Seconds = 0;
  sTime.SubSeconds = 0;
  sTime.DayLightSaving = RTC_DAYLIGHTSAVING_NONE;
  sTime.StoreOperation = RTC_STOREOPERATION_RESET;
  if (HAL_RTC_SetTime(&hrtc, &sTime, RTC_FORMAT_BIN) != HAL_OK)
  {
    Error_Handler();
  }
  sDate.WeekDay = RTC_WEEKDAY_MONDAY;
  sDate.Month = RTC_MONTH_MARCH;
  sDate.Date = 12;
  sDate.Year = 26;

  if (HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BIN) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN RTC_Init 2 */

  /* USER CODE END RTC_Init 2 */

}

/**
  * @brief TIM1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM1_Init(void)
{

  /* USER CODE BEGIN TIM1_Init 0 */

  /* USER CODE END TIM1_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};
  TIM_BreakDeadTimeConfigTypeDef sBreakDeadTimeConfig = {0};

  /* USER CODE BEGIN TIM1_Init 1 */

  /* USER CODE END TIM1_Init 1 */
  htim1.Instance = TIM1;
  htim1.Init.Prescaler = 0;
  htim1.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim1.Init.Period = 16999;
  htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim1.Init.RepetitionCounter = 0;
  htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
  if (HAL_TIM_Base_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim1, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_UPDATE;
  sMasterConfig.MasterOutputTrigger2 = TIM_TRGO2_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim1, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCNPolarity = TIM_OCNPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  sConfigOC.OCIdleState = TIM_OCIDLESTATE_RESET;
  sConfigOC.OCNIdleState = TIM_OCNIDLESTATE_RESET;
  if (HAL_TIM_PWM_ConfigChannel(&htim1, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
  sBreakDeadTimeConfig.OffStateRunMode = TIM_OSSR_DISABLE;
  sBreakDeadTimeConfig.OffStateIDLEMode = TIM_OSSI_DISABLE;
  sBreakDeadTimeConfig.LockLevel = TIM_LOCKLEVEL_OFF;
  sBreakDeadTimeConfig.DeadTime = 0;
  sBreakDeadTimeConfig.BreakState = TIM_BREAK_DISABLE;
  sBreakDeadTimeConfig.BreakPolarity = TIM_BREAKPOLARITY_HIGH;
  sBreakDeadTimeConfig.BreakFilter = 0;
  sBreakDeadTimeConfig.BreakAFMode = TIM_BREAK_AFMODE_INPUT;
  sBreakDeadTimeConfig.Break2State = TIM_BREAK2_DISABLE;
  sBreakDeadTimeConfig.Break2Polarity = TIM_BREAK2POLARITY_HIGH;
  sBreakDeadTimeConfig.Break2Filter = 0;
  sBreakDeadTimeConfig.Break2AFMode = TIM_BREAK_AFMODE_INPUT;
  sBreakDeadTimeConfig.AutomaticOutput = TIM_AUTOMATICOUTPUT_DISABLE;
  if (HAL_TIMEx_ConfigBreakDeadTime(&htim1, &sBreakDeadTimeConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM1_Init 2 */

  /* USER CODE END TIM1_Init 2 */

}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void)
{

  /* DMA controller clock enable */
  __HAL_RCC_DMAMUX1_CLK_ENABLE();
  __HAL_RCC_DMA1_CLK_ENABLE();

  /* DMA interrupt init */
  /* DMA1_Channel1_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel1_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel1_IRQn);
  /* DMA1_Channel2_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel2_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel2_IRQn);

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin_Pin */
  GPIO_InitStruct.Pin = B1_Pin_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(B1_Pin_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LD2_Pin */
  GPIO_InitStruct.Pin = LD2_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LD2_GPIO_Port, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
